site_name: WhiteTreeBible - Connections
site_url: https://connections.whitetreebible.com
use_directory_urls: true

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
  palette:
    - scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - mermaid-mod.css

extra_javascript:
  - https://unpkg.com/mermaid@10.9.0/dist/mermaid.min.js
  - mermaid-mod.js

nav:
  - Home: https://whitetreebible.com
  - Tools:
    - Connections: index.md
    - Blog: https://blog.whitetreebible.com/blog
  - About:
    - About Us: https://whitetreebible.com/about/about-us.md
    - Get Updates: https://whitetreebible.com/about/get-email-updates.md
    - Support Us: https://whitetreebible.com/about/support-us.md

plugins:
  - search
  - mermaid2
  - i18n:
      docs_structure: folder
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
          site_name: "WhiteTreeBible - Connections"

markdown_extensions:
  - footnotes   # needed for footnotes to render
  - attr_list   # needed for _target links to render
